server:
  port: 8761

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shenxuan52142/iiiicloud.git
          username: shenxuan52142
          password: 199351sx
          force-pull: true
          default-label: master
          skip-ssl-validation: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

