server:
  port: 8761

spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shenxuan52142/iiiicloud
          username: shenxuan1hao@163.com
          password: 199351sx
          force-pull: true
          default-label: master
          search-paths: configTest

